services:
  buddyscript-ui:
    container_name: buddyscript-ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "38291:8291"
    networks:
      - buddynet

networks:
  buddynet:
    external: true
