services:
  buddyscript-ui:
    container_name: buddyscript-ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "38291:8291"
    networks:
      - buddynet
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M

networks:
  buddynet:
    external: true
