server {
    listen 8291;

    client_max_body_size 15m;

    # Proxy to Backend securely within docker network
    location /api/ {
        # 'buddyscript-api:9384' explicitly maps to the backend compose service on our uncommon socket
        proxy_pass http://buddyscript-api:9384/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redirect bare domain to trailing slash
    location = / {
        return 301 $scheme://$host/login;
    }

    # Serve the React Application (SPA)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
